apiVersion: v2
name: fusion-backend
description: A Helm chart for Kubernetes
type: application
version: 0.1.0

dependencies:
  - name: postgresql
    version: 16.1.2
    repository: "https://charts.bitnami.com/bitnami"