apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
data:
  password: {{ .Values.postgresql.auth.password | b64enc }}
  emailPassword: {{ .Values.env.email.password | b64enc }}
  sessionSecret: {{ .Values.env.auth.sessionSecret | b64enc }}