name: Docker Image CI

on:
  push:
    branches:
      - "main"
    tags:
      - "v*"

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine Docker tag
        id: tag
        run: echo "tag=$(echo ${{ github.ref_name }} | sed 's|refs/heads/||' | sed 's|refs/tags/||')" >> $GITHUB_ENV

      - name: Extract repository name
        run: |
          repo_name=$(basename "${{ github.repository }}")
          echo "repository_name=$(echo $repo_name | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
          
      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ github.repository }}-${{ github.ref_name }}
          restore-keys: |
            ${{ runner.os }}-docker-${{ github.repository }}-
            
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ env.repository_name }}:${{ env.tag }}
